// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCaYS2YrJmgKDgYBI93f2MEZc-nw9kqRU8",
      authDomain: "fir-lab-12e91.firebaseapp.com",
      projectId: "fir-lab-12e91",
      storageBucket: "fir-lab-12e91.firebasestorage.app",
      messagingSenderId: "964111386211",
      appId: "1:964111386211:web:ff622548bd016120955a56");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyCyf0dUBELSyyknA_-vk6pCTtdVe-diCOA",
      authDomain: "fir-lab-12e91.firebaseapp.com",
      projectId: "fir-lab-12e91",
      storageBucket: "fir-lab-12e91.firebasestorage.app",
      messagingSenderId: "964111386211",
      appId: "1:964111386211:android:2831c8d5e6c5184e955a56");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-uvbrVfo-8H-NxBzS9vasFHIqw1grGFw',
    appId: '1:701077215139:ios:fd0dc63052f5451dc2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-flutter-codelab-957bb',
    storageBucket: 'fir-flutter-codelab-957bb.appspot.com',
    iosClientId:
        '701077215139-7j91ptognm4a5f7g3rj2pd9gpusb3gr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
